int led = LED_BUILTIN;
String in;
void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  pinMode(led, OUTPUT);
}

void loop() {
  // put your main code here, to run repeatedly:
  if(Serial.available()){
    in = Serial.readString();
    if(in.equals("FBCEBDEAEEAEBGADGCDBGADGAEEFBDAGCDAFCFGCEBEAEAGCCDADBDECECDBFACEBFIBGEAHBAGFBBBBBFCGKDDAHFJIFKEIBGFQDEFCLGCBFMBJFGGPJSHFEJPGGGEDEKHBCEDKADBJDPCGEFFCTCDKCANLAKSHHFFKMIFDBQFDFIABIFCOBCLIAGPJcCBEGODGIBNDDOCLCGFTBBbDATJKLHCFURNGCLDRFHDCECOKBXMDAMJEMFGWAJEQFAHAGFBBOJAJEHFSSHEIKALMKMDLbFBJEGAFGSGTEMGIBDNYKHMCIEGRFFUIMEBLNKEaLALLIQOLSMCQOiWMBPLKCQLJRCMJMkFDEGYBQDEPEVVBGIREMNKPZSeQOHBRBADDMEQLBIURVMOCBIGLGHCBUOGEMILBQOHOEFOFBUADFLMLPOCBGMDBRXkBPOXHEDKDFFBDTTHOHBJAPULOUBDWMECDCfeKMARTGACEQDIDBMRAcAGJINFPJDFRFBTHMUSOLNBCCNCFAGPCGeRWBKBTJBKCQIGIILXUNELiDLEEOIHIIKIPGRFQGEIAHJGKQDINBJCGQQNKMEBFOUKOAQBVEIFARDEFGGKBGUQAHTFDCHRBEEOOARZBLRhNQEHCbKJCKHBEWFaAPDJLQMQLLCNMHBAPICMOCRAKEAJGCDFLTMEKHBCIFGLEBITMLBOGHBMDIPMIAMAJFGHLEBFCMANKLPFEHKRAAOCIABGHMEFIGLGFCGANDEMFGDCFHDNBKBECOBEEDBPCFBMDCJDACIBBAHDBDCFCHJGBFCAGAAHGAAFKABFCBKHFAJCABDBKKDCJDBABDKFAEIGGFACGGEFBEHKHBEADBCBGDECCKJFBDDGHAADBBEEEEDHBBHMEBBAIADEBHAEECABABFFDBAGGGCAFADDDMCDCADKBDCBGDBBBAAAAADBBAFFAIDAABBDHDFGDBABFCFAGDCAADACDADAAADAACDAADCCDCCBDABCBEEBCEBBGCBCCAFHHFEFIFFFEFAACDDACCBECCECFEDBCADADBEDAAEAAAAAADDABBDABBBBB"))
    {
      int len = in.length();
      for (int i = 0; i < len; i++) {
        analogWrite(led, in[i] * 2);
        delay(5);
      }
    }
    else
      digitalWrite(led, LOW);
    in = "";
  }
}
